name: spell-check
on:
  push:
    branches:
      - '**'

jobs:
  spell-check:
    name: spell-check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - uses: check-spelling/check-spelling@main
